print("----------------------")
print("- Hi!, I would need some personal information to start the program c: ")
print("- So.. Whats your name?")
name = input("+ My name is: ")
print("- Cool," + name + "!")
print("----------------------")
print("- How old are you?")
age = input("+ I am: ")
print("- Okay, so your name is " + name + " and you are " + str(age) + " years old, Great! c:")
print("----------------------")
favcolor = input("-  Well, everybody has a favorite color, Whats yours? \n+ ")
print("- I like " + favcolor + ", is a beautiful color.")
print("----------------------")
print("- Now lets play with numbers!")
print("- This is a very basic calculator.")
print("----------------------")
num1 = input("- Write a number: ")
num2 = input("- Now write another number: ")
sumresult = float(num1) + float(num2)
mulresult = float(num1) * float(num2)
divresult = float(num1) / float(num2)
print("- The sum of those numbers is: " + str(sumresult))
print("- if we multiply those numbers is: " + str(mulresult))
print("- And the division is: " + str(divresult))
print("----------------------")